### PR TITLE
Allow to override a higher version in next level when promote a release or assignment

### PR DESCRIPTION
**Pull request by zhouqr2000**

### CODE REVIEW

**Comment by jdewinne** [comment]
Some questions

+ Is this change depending on a certain ISPW version? If so, can that be mentioned in the [readme](https://github.com/xebialabs-community/xlr-ispw-plugin/blob/master/README.md)?
+ If the `override` is only available in newer versions, will the api be backwards compatible. Meaning, will the plugin still work if `override` is part of the json content for older versions of ISPW?
+ Can you generate a new screenshot for the promote task as currently shown in the [readme](https://github.com/xebialabs-community/xlr-ispw-plugin/blob/master/README.md)

**Review by jdewinne — COMMENTED** [review]
See previous comment.

**Comment by zhouqr2000** [comment]
Hi @jdewinne, I updated the promote screenshot and added a new CHANGELOG.md. thanks.

**Comment by jdewinne** [comment]
Thanks for the CHANGELOG. Did you have something in mind for the Changelog? I like the idea! Would be nice to see github processing it, and using it within the release notes.
Will merge. Let me know via this thread or via email if you want to discuss the Changelog usage further...

**Comment by zhouqr2000** [comment]
I think whenever a pull request created, the CHANGELOG is required to be updated to add one or more new entry to reflect the new feature or fix. The entry should be located under the next published version. In this case, you don't need to maintain it by yourself, instead, by the contributor. I doubt GitHub has an automatic tool to process it.

**Pull request merged**
